### ISSUE TITLE
Typed responses with status codes

### ISSUE THREAD

**Issue by alex-dixon** [sukovanej/effect-http#120]
Hello again. 

I was wondering if you'd consider responses that allow type validation alongside status codes and headers.

Using `Response` allows a custom response status code and headers but allows a body that may violate the API contract:
https://github.com/sukovanej/effect-http/blob/1ce5691fa95fa8196e59d4b267e60e1e17284a4d/examples/response-object.ts#L16

**Comment by sukovanej** [comment]
That sounds reasonable and actually I already had something like this but I got rid of it when I moved to standardized `Request` / `Response` objects. So, yes I think the type-safety is worth it. I need to encode response headers using `Schema` in the `Api` anyway, so I'll do it together probably.

**Comment by alex-dixon** [comment]
Thanks! Yes, I normally prefer transport agnostic as you have now, but status codes in the api type definition layer seems appropriate given http is presumed. If all http request response definitions are there, then handler return values can be type checked against them, sample api responses could be generated with fast check, and fuller open api contracts with status codes etc. could be generated

**Comment by sukovanej** [comment]
Released in [v0.19.0](https://github.com/sukovanej/effect-http/releases/tag/v0.19.0). Closing this issue. Ping me on the effect discord or feel free to open an issue in case you have any comments.
