### ISSUE TITLE
Optional query parameters

### ISSUE THREAD

**Issue by vecerek** [sukovanej/effect-http#158]
Hi @sukovanej 👋 First of all, this library looks super promising! I'm very happy to have started fiddling with it 🙂 

I'm trying to migrate my own fp-ts-based HTTP clients to use `effect-http`. However, I've hit a wall since I'm unable to express optional query parameters. I was hoping the following (or something similar) would work:

```ts
import * as schema from "@effect/schema/Schema";
import { pipe } from "effect";
import * as http from "effect-http";

export const api = pipe(
  http.api(),
  http.get("userById", "/api/users/:userId", {
    response: schema.struct({ name: schema.string }),
    params: { userId: schema.string },
    // @ts-expect-error Type 'Schema<string | undefined, string | undefined>' is not assignable to type 'Schema<string, any>'.
    query: {
      include_deleted: schema.union(schema.string, schema.undefined),
    },
    headers: {
      authorization: schema.string,
    },
  })
);
```

Looking more at the REAMDE, I haven't seen any mention of optional query parameters or request headers. Is there a specific reason for the lack of optional inputs, or would this be an acceptable feature request?

**Comment by sukovanej** [comment]
Hey and thanks for the interest. You're right, optional query parameter is not supported. Probably `Schema.optional` is the most sensical option to employ to represent it for `params`, `query` and `header` specs. Your example would look like this

```ts
import * as schema from "@effect/schema/Schema";
import { pipe } from "effect";
import * as http from "effect-http";

export const api = pipe(
  http.api(),
  http.get("userById", "/api/users/:userId", {
    response: schema.struct({ name: schema.string }),
    params: { userId: schema.string },
    query: {
      include_deleted: schema.optional(schema.string),
    },
    headers: {
      authorization: schema.string,
    },
  })
);
```

I'm in the middle of a bigger inner refactoring. I'll implement the optional headers and path/query parameters right after that.

**Comment by vecerek** [comment]
Yeah, `schema.optional` was my first approach, as well. Since you happen to be in the middle of a refactoring, what would you think about the following API change? Currently, the `http[method]` functions' 3rd argument expects the user to provide a schema for `response` and structs of schema for `params`, `query`, and `headers`. What if those were replaced by a `request` field with its own schema like so?

```ts
import * as schema from "@effect/schema/Schema";
import { pipe } from "effect";
import * as http from "effect-http";

export const api = pipe(
  http.api(),
  http.get("userById", "/api/users/:userId", {
    response: schema.struct({ name: schema.string }),
    request: schema.struct({
      params: schema.struct({
        userId: schema.string,
      }),
      query: schema.partial({
        include_deleted: schema.string,
      }),
      headers: schema.struct({
        authorization: schema.string,
      })
    }),
  })
);
```

**Comment by sukovanej** [comment]
Something like this might be the way to go as well. I like the idea of branching the `response` and `request` schemas structurally as you propose. 👍

**Comment by sukovanej** [comment]
Released in [v0.20.0](https://github.com/sukovanej/effect-http/releases/tag/v0.20.0).

Your code can be written as follows. 

Side note: the `include_deleted` parameter is probably a boolean based on the name, I put the `SchemaBooleanFromString` into the example. Check it out, even if you're implementing the client side only, it will force you to put a boolean there and it will serialize it to string under the hood, better typing, better safety 🙂 . 

```ts
import { pipe } from "@effect/data/Function";
import * as Effect from "@effect/io/Effect";
import * as Schema from "@effect/schema/Schema";

import * as Http from "effect-http";

const SchemaBooleanFromString = pipe(
  Schema.literal("true", "false"),
  Schema.transform(
    Schema.boolean,
    (i) => i === "true",
    (o) => (o ? "true" : "false"),
  ),
);

export const api = pipe(
  Http.api(),
  Http.get("userById", "/api/users/:userId", {
    response: Schema.struct({ name: Schema.string }),
    request: {
      params: Schema.struct({
        userId: Schema.string,
      }),
      query: Schema.struct({
        include_deleted: Schema.optional(SchemaBooleanFromString),
      }),
      headers: Schema.struct({
        authorization: Schema.string,
      }),
    },
  }),
);
```

**Comment by vecerek** [comment]
@sukovanej I am astonished at how fast this got implemented. Thank you so much! ❤️ Also thanks for the recommendation, `BooleanFromString` it will be 🙂

**Comment by danielo515** [comment]
Is this the current right approach this?

**Comment by sukovanej** [comment]
Yep, use `Schema.optional` to represent a query param which doesn't need to be provided at all. Note that code snippets in this issue are probably outdated, please check out the latest readme. Also, you very likely know but just in case somebody else comes across this thread, be aware this library is deprecated in favour of `HttpApi*` modules from the `@effect/platform`.

**Comment by danielo515** [comment]
Thank you for your response. I am aware this library is deprecated, but I am just using it on a side project and I don't have the time to migrate now.
I have currently like this:
```ts
const PaginationQuery = Schema.Struct({
  page: Schema.optional(Schema.NumberFromString),
  pageSize: Schema.optional(Schema.NumberFromString),
});
//....
  Api.addEndpoint(
    pipe(
      Api.get("list-expenses", "/api/expenses", {
        description: "List expenses",
      }),
      Api.setSecurity(cookieSecurity),
      Api.setRequestQuery(PaginationQuery),
      Api.setResponseBody(PaginatedResponse)
    )
  ),
```
Does that allow for completely empty request query?
