### ISSUE TITLE
Migrate to @effect/platform/Http

### ISSUE THREAD

**Issue by jessekelly881** [sukovanej/effect-http#226]
It would be awesome if this lib migrated to the @effect/platform html client+server api now that that has seen some progress. :)

**Comment by sukovanej** [comment]
Definitely, that's the plan! I'm waiting for the /platform API to stabilize. After that once familiarize myself with it, I'll proceed with the rewrite.

**Comment by sukovanej** [comment]
Hola, released 🎉 . There's quite a lot of changes in the lib's API. Check the [release notes](https://github.com/sukovanej/effect-http/releases/tag/v0.37.0), examples and readme.
