### ISSUE TITLE
Expose openapi.json spec

### ISSUE THREAD

**Issue by sparrovv** [sukovanej/effect-http#227]
It would be nice to expose `/openapi.json` endpoint that returns the OpenAPI spec, as then it could be used to create http clients in other languages, or it could be used in postman, etc.

**Comment by sukovanej** [comment]
Like it 👍 . It should be pretty straightforward. Feel free to open a MR, otherwise, I'll prepare and release it probably during the weekend.

**Comment by sukovanej** [comment]
Released.

**Comment by sparrovv** [comment]
Oh nice, thank you 🙇 🔝
