### ISSUE TITLE
Access logging

### ISSUE THREAD

**Issue by sparrovv** [sukovanej/effect-http#230]
Hi,

I'm trying to understand how the logging works and what's currently available.

I was trying to search in examples but didn't find a solution to get these in the log:
- entries for 404s (atm incorrect requests are not showing up in the log, which might be a feature or a bug 😅 )
- remote IP address
- HTTP status code of the response

Are these supported or something that needs changes?

Thanks 🙇

**Comment by sukovanej** [comment]
Hey, to support these we need to make some adjustions. Currently, the logging is quite dummy and 404s for unhandled paths are not covered at all, see the [access logging extension](https://github.com/sukovanej/effect-http/blob/master/src/Extensions.ts#L113) and [error logging extension](https://github.com/sukovanej/effect-http/blob/master/src/Extensions.ts#L174).

I'm in front of a rewrite of the internals to Http from `@effect/platform` and the logging we'll be probably imlpemented using [middlewares](https://effect-ts.github.io/platform/platform/Http/Middleware.ts.html). So I'll probably enable the listed items along with the rewrite.

**Comment by sparrovv** [comment]
Got it, thanks for the update. Looking forward to using these additions :-)

**Comment by sukovanej** [comment]
Hey, the rewrite was released. With the newest version, you can compose the `App` built by `effect-http/RouterBuilder` with the [@effect/platform Middleware](https://effect-ts.github.io/platform/platform/Http/Middleware.ts.html). In the middleware, you can access both [ServerRequest](https://effect-ts.github.io/platform/platform/Http/ServerRequest.ts.html) and [ServerResponse](https://effect-ts.github.io/platform/platform/Http/ServerResponse.ts.html) and use it however you like.

I'll probably prepare a section about middlewares, routers and the stuff from @effect/platform in the readme later.
