### ISSUE TITLE
Add option to return all schema validation errors

### ISSUE THREAD

**Issue by alex-dixon** [sukovanej/effect-http#244]
Hello! I was wondering if you would be interested in supporting an option to return all schema errors. By default schema returns the first one. All errors must be opted into with `parse(Type)(x, {errors: "all")`. 

Places I could find parse is called:

https://github.com/sukovanej/effect-http/blob/88b370ec97674890327b527c4d6db63c5547fba9/src/Server.ts#L90

https://github.com/sukovanej/effect-http/blob/88b370ec97674890327b527c4d6db63c5547fba9/src/Client.ts#L149

**Comment by sukovanej** [comment]
Hey, that looks reasonable. We can even make it configurable on `Api` / `ServerBuilder` level. I'll take a look and potentially implement it during the weekend.

**Comment by sukovanej** [comment]
Released. You can use [options](https://sukovanej.github.io/effect-http/modules/RouterBuilder.ts.html#options-interface) to specify the `AST.ParseOptions` as a second optional parameter of the `RouterBuilder.make`.

```ts
RouterBuilder.make(api, { parseOptions: { errors: "all" } })
```
