### ISSUE TITLE
Common headers server side

### ISSUE THREAD

**Issue by benjstephenson** [sukovanej/effect-http#258]
Hi, really enjoying exploring the lib!
I was wondering if there is any way to add in common response headers to the server? 
E.g adding in CORS headers at the moment looks like it needs a header schema needs to be added to each response and then instantiated in each handler.
I though this could be achieved by creating an `afterHandler` extension but I'm not too sure how to modify the response object.

**Comment by benjstephenson** [comment]
Oh, I see now the extensions give you access to the Response object directly!
Nvm 😅

**Comment by benjstephenson** [comment]
I'd be keen to help out with some PRs if you have a task list 👍

**Comment by sukovanej** [comment]
Awesome. Unfortunately, it is now pretty much a matter of experimentation and testing and I don't have an item list with a clear DoD. On the other hand, it might be worth to create an issue with at least high level ideas and plans and maybe some nice tasks will pop out of it. I'll try to prepare it 👍.
