### ISSUE TITLE
Testing client appears to expect only JSON payloads

### ISSUE THREAD

**Issue by alex-dixon** [sukovanej/effect-http#277]
We're seeing some issues with the testing client and a multipart form data payload. I found this which makes it look like all requests with a body are transformed to json with application/json headers. https://github.com/sukovanej/effect-http/blob/8cc40b6dc9aceb644bba443e4fb1449a075394a7/src/Testing.ts#L77

Is the testing client still a work in progress or is it ok to assume it has parity with the server?

**Comment by sukovanej** [comment]
Hey, the testing client will be reworked along with the server implementation using the `@effect/platform`. For now, I prepared a quick fix. Please, let me know if the problem resolves on your end with the new version. Thanks for the report!

**Comment by sukovanej** [comment]
Hey, in the lib tests I have [an example case](https://github.com/sukovanej/effect-http/blob/master/tests/testing-client.test.ts#L199) with the form data. The overall usage and specification of form data is currently not handled well, there is no automatic validation and the OpenAPI spec is basically incorrect. I'm gonna need to put more work into that. But it should be usable on the server and client and with the @effect/platform being the underlying mechanism, it should be very flexible.
