### ISSUE TITLE
CORS header not returned in OPTIONS call

### ISSUE THREAD

**Issue by benjstephenson** [sukovanej/effect-http#283]
I've got an `afterHandlerExtension` defined as follows

```ts
const CorsExtension = Http.afterHandlerExtension("corsHeader", (_req, resp) => {
  resp.headers.set("Access-Control-Allow-Origin", "*")
  return Effect.succeed(resp)
})
...

export const ApiServer = pipe(
  Api,
  Http.server,
  Http.addExtension(CorsExtension),
  ...add handlers
  Http.exhaustive
)
```

If I make a call to a defined endpoint directly, then I can see the `Access-Control-Allow-Origin` header on the response.  However, when a request is made from our front end and the browser initially sends the OPTIONS request, the header is not present on the response and we get a  `CORS Missing Allow Origin` error.

Am I configuring this incorrectly?

**Comment by benjstephenson** [comment]
So I've tried applying the cors middleware to the underlying Express app like so

```ts
export const HttpServerLive = Layer.scopedDiscard(
  Effect.flatMap(
    Effect.config(httpServerConfig),
    cfg =>
      AnimalApiServer.pipe(
        Http.express(),
        Effect.map(express => express.use(cors())),
        Effect.flatMap(Http22.listenExpress({ port: cfg.port }))
      )
  )
)
```

but that doesn't seem to work either; I think because the `Http.express()` call applies the route handlers before it returns the express instance which I then add the cors middleware to.  The order that you add middleware and handlers in express matters, iirc.

**Comment by sukovanej** [comment]
Hey, it might be a problem with the order. Anyway, I'm close to finishing a first version of the big rewrite onto `@effect/platform` (https://github.com/sukovanej/effect-http/pull/287). It will drop the express  and instead it will give the user an ability to manipulate `Router` and `App` from the `@effect/platform/Http` directly if needed. Thus, the extension API in here will be discarded in favor of their `Middleware` or whatever `App` / `Router` transformation. Then, either me in this lib or maybe someone in the community as a separate pkg might prepare a CORS "plugin" you could use.

**Comment by sukovanej** [comment]
Hey, the @effect/platform rewrite was released. You can use the [@effect/platform middleware](https://effect-ts.github.io/platform/platform/Http/Middleware.ts.html) now to attach necessary headers or respond to the OPTION requests. Some time later, I'll probably include the CORS middleware directly into the lib (or might be worth contributing directly into the @effect/platform), but for now you should be able to deal with it in the user-space.
