### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by jessekelly881** [sukovanej/effect-http#289]
"Some descriptions are provided from the built-in @effect/schema/Schema combinators. For example, **the usage of Schema.int() will result in "a positive number" description** in the OpenApi schema. One can also add custom description using the Schema.description combinator."

I hope this isn't the case. Lol

**Comment by sukovanej** [comment]
Opps, I'll need to go through the readme and check for old stuff and mistakes (or give it to a chatgpt 😄 ). I probably meant `Schema.number.pipe(Schema.int(), Schema.positive())` will result in the mentioned description.

**Comment by jessekelly881** [comment]
Lol. No worries. I figured as much. `Schema.Int.pipe(Schema.positive())` might be slightly better btw.

**Comment by sukovanej** [comment]
Fixed 👍
