### ISSUE TITLE
Content-Type header seems to be fixed to application/json

### ISSUE THREAD

**Issue by p3et** [sukovanej/effect-http#320]
Hello,
I want to set _content-type_ header to _text/plain_ in a response to a get request. I tried your [example](https://github.com/sukovanej/effect-http#responses) but without _Schema.struct_ it does not compile. The code below compiles but the response has still _application/json_. Could you please tell me how to set _content-type_ header correctly?

```typescript
import {Effect} from "effect";
import {NodeServer} from "effect-http";
import {PrettyLogger} from "effect-log";
import {RouterBuilder} from "effect-http";
import {Api} from "effect-http";
import * as Schema from "@effect/schema/Schema";

export const api = Api.api({title: "Example API"}).pipe(
  Api.get("root", "/", {
    response: {
      status: 200,
      content: Schema.string,
      headers: Schema.struct({"Content-Type": Schema.string}),
    },
  }),
);

export const app = RouterBuilder.make(api).pipe(
  RouterBuilder.handle("root", () =>
    Effect.succeed({
      content: "Hello World!",
      status: 200 as const,
      headers: {"content-type": "text/plain"},
    }),
  ),
  RouterBuilder.build,
)

const program = app.pipe(
  NodeServer.listen({port: 3000}),
  Effect.provide(PrettyLogger.layer()),
);

Effect.runPromise(program);
```
```json
{
"dependencies": {
    "@effect/schema": "^0.48.3",
    "effect": "2.0.0-next.55",
    "effect-http": "^0.39.0",
    "effect-log": "^0.23.1"
  },
  "devDependencies": {
    "prettier": "^3.1.0",
    "tsx": "^4.1.3",
    "typescript": "^5.2.2"
  }
}
```

**Comment by sukovanej** [comment]
Hey, for non-json responses, you'd currently need to use `RouterBuilder.handleRaw` and construct the response yourself.

```ts
import * as Http from "@effect/platform/HttpServer";

...

export const app = RouterBuilder.make(api).pipe(
  RouterBuilder.handleRaw(
    "root",
    Http.response.text("Hello World!", {
      status: 200 as const,
      headers: { "content-type": "text/plain" },
    }),
  ),
  RouterBuilder.build,
);
```

I still haven't decided on a way to encode this information in the `Api.Api` spec. I'll probably need to introduce a new specifier for it in the `response` spec.

**Comment by p3et** [comment]
Thanks for the quick action! I think it would be really a good idea to make this somehow part of the Api spec. I really think the seemless integration of API and effect makes your project a real gem.

**Comment by sukovanej** [comment]
Yes definitely. I started prototyping an idea where the content type (along with content `A -> string` encoding) would be configured using a `Schema` annotation - [example](https://github.com/sukovanej/effect-http/blob/feat/schema-http-specific-annotations/examples/plain-text.ts). I'm gonna see where that'll lead me and link a potential MR with this issue. Thank you!

**Comment by sukovanej** [comment]
Sorry for late ping. I took a different path and introduced the `Representation` structure and described it in the README. Feel free to check it. 

It is a general solution providing a way to represent data for the client and the content-type header is a natural part of it. It produces the output based on the incoming `Accept` header but if you set only a single representation, the endpoint will always produce the given content-type.

**Comment by sukovanej** [comment]
Hey, closing this one, I didn't notice more requests on this topic. Later on, we might attempt to think through a better abstraction for dealing with different content types.
