### ISSUE TITLE
Type error with Http.get

### ISSUE THREAD

**Issue by jessekelly881** [sukovanej/effect-http#33]
Hi! I just ran across this library and it looks great! I was playing around with the examples though and was having some type issues though. Specifically with the Http.get function. I get "Expected 0 arguments, but got 3". Currently I'm using version 0.1.0 but I've tested it with earlier versions. 

https://codesandbox.io/p/sandbox/winter-field-30ikt5?file=%2Fsrc%2Findex.ts&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A9%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A9%7D%5D

**Comment by sukovanej** [comment]
Hey there, I'm not sure about the type error in an editor about the number of arguments, that one's weird 🤔 . But the one from ts-node script is definitely related to mismatching version of /schema. Please, try upgrading the `@effect/schema` to latest, I can see you have `^0.11.1` and `effect-http` has `^0.17.2`.

**Comment by sukovanej** [comment]
And I just noticed a missing dependency in `effect-http` and just published a fix version. So also please use version `0.1.1` of `effect-http` 😅

**Comment by jessekelly881** [comment]
Hmm. I updated everything to latest and still have issues.

<img width="1440" alt="Screen Shot 2023-04-26 at 12 44 56 PM" src="https://user-images.githubusercontent.com/22938931/234672844-5ebc3d92-fa5e-4e75-9ea4-27b2012c1585.png">

**Comment by jessekelly881** [comment]
I actually just cloned the repo and there are type issues with Http.get, .post, etc. in the examples as well. 

<img width="1440" alt="Screen Shot 2023-04-26 at 12 50 21 PM" src="https://user-images.githubusercontent.com/22938931/234674144-0c518790-c791-4151-b8ba-cb3e22e84d95.png">
<img width="1440" alt="Screen Shot 2023-04-26 at 12 50 32 PM" src="https://user-images.githubusercontent.com/22938931/234674178-3c3542cc-8338-4855-86dd-f52521132658.png">

**Comment by jessekelly881** [comment]
The issue seems to be this line. Removing the _consts_ fix the type def for me. I think using const in a generic only works with the function keyword and not when defining functions using const. Although maybe that's been updated. 

```js
export const endpoint =
  (method: OpenApi.OpenAPISpecMethodName) =>
  <const Id extends string, const I extends InputSchemas>(
    id: Id,
    path: string,
    schemas: I,
  ) =>
```

**Comment by jessekelly881** [comment]
I figured out this issue. I was running an older version of typescript. I had the right version of typescript installed on the sandbox but I guess it wasn't active. Testing it locally with the right version works. :) Sorry for the bother.
