### ISSUE TITLE
Using `MockClient.make` crashes trying to encode request schema

### ISSUE THREAD

**Issue by benjstephenson** [sukovanej/effect-http#356]
I'm using effect-http to model an external Api that I'm calling using `Client.make` (which is a really cool feature!) and it works great.  But now I want to generate a mock client to write some tests with, so I've got 

```ts
const AnimalAdapterClientTest = Layer.succeed(AnimalAdapterClient, MockClient.make(animalAdapterApi))
```

And I get an error at startup:
```
/Users/bste/ghq/gitlab.com/ezyvet/application/hypr/launchpad/node_modules/.pnpm/@effect+schema@0.53.1_effect@2.0.0-next.60_fast-check@3.14.0/node_modules/@effect/schema/src/Parser.ts:273
  switch (ast._tag) {
              ^
TypeError: Cannot read properties of undefined (reading '_tag')
```

I've had a dig through the code and it looks like in [`effect-http/internal/utils`](https://github.com/sukovanej/effect-http/blob/bab610c3bdc3cf2c7e2838da56f47611872164a3/src/internal/utils.ts#L11C1-L11C1) when we check if the request params schemas is `IgnoredSchemaId` the test returns `false` so we try to call `Schema.encode`.

Printing the `requestSchemas` to the console from the utils file, I can see params is set to `Symbol(effect-http/ignore-schema-id)` 
```ts
{
  query: SchemaImpl {
    ast: {
      _tag: 'TypeLiteral',
      propertySignatures: [Array],
      indexSignatures: [],
      annotations: {}
    },
    [Symbol(@effect/schema/Schema)]: { From: [Function: From], To: [Function: To] }
  },
  params: Symbol(effect-http/ignore-schema-id),
  body: Symbol(effect-http/ignore-schema-id),
  headers: SchemaImpl {
    ast: {
      _tag: 'TypeLiteral',
      propertySignatures: [Array],
      indexSignatures: [],
      annotations: {}
    },
    [Symbol(@effect/schema/Schema)]: { From: [Function: From], To: [Function: To] }
  }
}
```
Logging out the whole imported Api object shows that `IgnoredSchemaId` looks fine:

```ts
[Object: null prototype] {
  default: {
    ApiGroupTypeId: Symbol(effect-http/Api/ApiGroupTypeId),
    ApiTypeId: Symbol(effect-http/Api/ApiTypeId),
    FormData: SchemaImpl {
      ast: [Object],
      [Symbol(@effect/schema/Schema)]: [Object]
    },
    IgnoredSchemaId: Symbol(effect-http/ignore-schema-id),
    ...
  }
}
```

but if I print out the field with `console.log(Api__namespace.IgnoredSchemaId)` then I get `undefined`.
I'm not too sure what to check next.

Versions of packages are:
effect: 2.0.0-next.60
effect-http: ^0.45.1
@effect/platform-node: ^0.37.6
@effect/schema: ^0.53.1

**Comment by sukovanej** [comment]
Hey, thanks for the report. Could you please update to [0.45.2](https://github.com/sukovanej/effect-http/releases/tag/v0.45.2) and try again? The mock client implementation still used a legacy version of the request encoding, I updated it to use the same as used for the real client.

**Comment by benjstephenson** [comment]
Works like a charm, thanks for the quick fix! :)
