### ISSUE TITLE
Option to disable swagger ui in latest revision

### ISSUE THREAD

**Issue by alex-dixon** [sukovanej/effect-http#377]
Hello! We recently upgraded to the latest version. We were wondering if there's still.a way to optionally disable the swagger ui functionality? I haven't been able to find it.

**Comment by sukovanej** [comment]
Hey, as it was an option of the express functionality it got removed. I can probably add it as an option of the router builder. BTW, what is the reason for you to disable it?

**Comment by alex-dixon** [comment]
Makes sense, thank you.

> what is the reason for you to disable it?

Mostly security. We're seeing it pop up in tests also when building/tearing down the test server....so could make tests a bit faster if we could disable it there also I guess

**Comment by sukovanej** [comment]
Reasonable 👍. I'll add it back as an option of the RouterBuilder.

**Comment by sukovanej** [comment]
Released in 0.48. Use `RouterBuilder.make(api, { enableDocs: false })`.
