### ISSUE TITLE
Extra "/" in client when using baseURL as new URL()

### ISSUE THREAD

**Issue by alex-dixon** [sukovanej/effect-http#378]
https://github.com/sukovanej/effect-http/blob/00238724895a9ed15017fdeff4b8a4d122f68eed/src/internal/client.ts#L30

It looks like new URL().toString() has some interesting behavior...

```
new URL("http://google.com").toString()
'http://google.com/'
```

This ends up with the client sending requests to /search as //search

For now we're using a string which works fine.

**Comment by sukovanej** [comment]
I remember I was fighting with the `URL` myself so this issue was a final trigger to prepared a MR where I simply replaced `URL` by raw strings. `@effect/platform` uses strings in the public API as well anyway.

**Comment by sukovanej** [comment]
Version 0.48 enforces a string for the `baseUrl` so there should no more surprises with the `URL` usage.
