### ISSUE TITLE
form-data content-type support?

### ISSUE THREAD

**Issue by admsmth** [sukovanej/effect-http#392]
Hello,

I've recently upgraded to a newer version of this package (0.46.2) and am now running into issues with the server failing to process requests with FormData content-types.

The requests fail prior to reaching our registered handler for the given endpoint with the following error. It seems like there may be a bug with how form-data requests are decoded/parsed prior to being passed on to the endpoint's registered handler:
```
{
  "_tag": "RequestError",
  "request": {
    "_tag": "ServerRequest",
    "method": "POST",
    "url": "/coi_request",
    "originalUrl": "/coi_request",
    "headers": {
      "authorization": "--redacted--",
      "user-agent": "PostmanRuntime/7.36.0",
      "accept": "*/*",
      "cache-control": "no-cache",
      "postman-token": "0b7ca553-40ef-48aa-94b1-866d638875ec",
      "host": "localhost:8080",
      "accept-encoding": "gzip, deflate, br",
      "connection": "keep-alive",
      "content-type": "multipart/form-data; boundary=--------------------------707399609773474252081923",
      "content-length": "318"
    }
  },
  "reason": "Decode",
  "error": {}
}
```

Are there any known limitations to using FormData content-types/are you aware of any breaking changes to FormData content-type handling since the big re-write post v0.32.0?

Likewise, is there any way I can register a handler that bypasses the default request payload decoding behavior and handle type validations manually within the endpoint's handler?

Thanks for any help you can provide.

**Comment by sukovanej** [comment]
Hey, there was a big rewrite some time ago where the internals started relying on the `@effect/platform` and the form-data was handling was affected as well. Please refer to the [form-data example](https://github.com/sukovanej/effect-http/blob/master/examples/form-data.ts).

Please be aware that over all the file handling is not handled super well yet. Notably, the OpenAPI spec is inprecise. There is tons of room for improvement and expect some changes in the future. 🙂

**Comment by admsmth** [comment]
Thanks, this helped us fix the problem
