### ISSUE TITLE
Issues resolving OpenAPI components with subset of `Schema.optional` API

### ISSUE THREAD

**Issue by TylorS** [sukovanej/effect-http#471]
Hello again 👋 

I think I've encountered a small bug somewhere within the OpenAPI integration being unable to create "Components" with schemas containing identifiers when some of its property signatures are optional, but only a subset of them.

I _think_ it has to do with the `optionalToRequired` transformation that takes place internally to Schema, but I'm not too positive after looking only a bit briefly.

```ts
import * as S from '@effect/schema/Schema';
import { Api, OpenApi } from 'effect-http';

const schema = S.struct({
  // Does NOT work
  // a: S.optional(S.Date, { nullable: true, exact: true, as: 'Option' }),
  // b: S.optional(S.Date, { nullable: true, default: () => new Date(), }),
  // c: S.optional(S.Date, { exact: true, default: () => new Date() }),
  // d: S.optional(S.Date, { exact: true, as: 'Option' }),
  // e: S.optional(S.Date, { nullable: true, as: 'Option' }),
  // f: S.optional(S.Date, { as: 'Option' }),
  // Does Work
  // y: S.optional(S.Date, { exact: true }),
  // z: S.optional(S.Date),
}).pipe(S.identifier('Foo'));

const api = Api.api({ title: 'Example' }).pipe(
  Api.get('getFoo', '/:foo', {
    request: {
      params: S.struct({
        foo: S.string,
      }),
    },
    response: schema,
  })
);

console.log(OpenApi.make(api));
```

**Comment by sukovanej** [comment]
Hey, thank you. Indeed, it was a problem with a transformation which was not considered for components. I didn't check the impl in effect/schema but evidently, in the non working optional cases you provided the whole `struct` is converted onto a transformation AST node. I have a schema-openapi fix [here](https://github.com/sukovanej/schema-openapi/pull/194/files) and I'll update it in here in a moment.

**Comment by sukovanej** [comment]
Please, try with the latest version.

**Comment by TylorS** [comment]
@sukovanej The latest build has fixed this issue, thank you!
<img width="700" alt="Screenshot 2024-03-15 at 4 34 04 PM" src="https://github.com/sukovanej/effect-http/assets/6282473/aaf3412b-cc57-428a-b9d3-a6cf839120e5">
