### ISSUE TITLE
How to mount an API under a base path

### ISSUE THREAD

**Issue by adrian-gierakowski** [sukovanej/effect-http#508]
Say I’ve got an API with endpoints /a and /b
How could I create a server which would serve them at /prefix/a and /prefix/b?

thanks!

**Comment by sukovanej** [comment]
Maybe there's a better API for that in `@effect/platform` but something like this should do

```ts
const app = RouterBuilder.make(api).pipe(
  ...,
  RouterBuilder.build,
  (app) => HttpServer.router.empty.pipe(HttpServer.router.mountApp("/prefix", app))
)
```

`RouterBuilder.build` returns the `@effect/platform`'s `App`, so from that point you can do whatever with that using `App` / `Router` combinators.

One more thing, if you're adding a prefix, you could also benefit from making this information available in the OpenApi using `servers` field when defining an `Api`

```ts
const api = Api.make({ servers: [{ url: '/prefix', description: 'my server name' }] })
```

**Comment by adrian-gierakowski** [comment]
Thanks! My first attempt was adding url in servers, but that didn’t work, lol 

I’ll try that tomorrow and report back

**Comment by ssijak** [comment]
@adrian-gierakowski you did not report back

**Comment by adrian-gierakowski** [comment]
My apologies. This approach worked for me, thanks!

**Comment by jpaju** [comment]
Would be awesome if this feature would be support natively in effect-http! I often have the case that I want to prefix some endpoints with `/v1` etc. and having to remember to keep the docs in sync can be cumbersome
