### ISSUE TITLE
Authorize swagger button doesn't appear any more

### ISSUE THREAD

**Issue by kattsushi** [sukovanej/effect-http#646]
<img width="122" alt="Screenshot 2024-08-03 at 10 50 33 a m" src="https://github.com/user-attachments/assets/c77cf7c2-e594-4d91-ab0b-8308f9ce2c2a">
<img width="1141" alt="Screenshot 2024-08-03 at 11 03 53 a m" src="https://github.com/user-attachments/assets/1736f9bc-d898-461d-bbd3-4d59f976b467">

since some previous versions the Authorize swagger button it doesnt appear any more to setup the bearer token

here my implementation for reference
```
export const authSecurity = pipe(
  Security.bearer({ name: 'AuthToken', description: 'token', bearerFormat: 'JWT' }),
  Security.mapEffect((creds) => {
    if (creds === 'secret') {
      return T.succeed(creds)
    }
    return HttpError.unauthorized('Invalid token')
  }),
)

export const createUserEndpoint = Api.post('createUser', '/api/users').pipe(
  Api.setRequestBody(UserWithOutId),
  Api.setResponseBody(User),
  Api.setSecurity(authSecurity),
)

export const UserApiGroup = ApiGroup.make('Users', {
  description: 'All about Users',
}).pipe(
  ApiGroup.addEndpoint(createUserEndpoint),
)

export const GatewayApi = Api.make({
  title: 'API Gateway',
  servers: [{ url: 'http://localhost:3001' }],
}).pipe(
  Api.addGroup(UserApiGroup),
)

export const GatewayRouterBuilder = RouterBuilder.make(GatewayApi, {
  docsPath: '/api',
  parseOptions: { errors: 'all' },
}).pipe(
  RouterBuilder.merge(UserRouterBuilder),
  RouterBuilder.build,
  Middlewares.errorLog,
)

const ApiLayer = pipe(
  Layer.mergeAll(PrettyLogger.layer(), DotEnv.setConfigProvider()),
  Layer.provideMerge(NodeContext.layer),
  OpenTelemetryLayer({ serviceName: 'Api Gateway' }),
)

const main = pipe(
  EnvConfig,
  T.tap((config) => T.logInfo(`Starting Api Gateway... visit http://localhost:${config.port}/api to see the docs`)),
  T.flatMap((config) => GatewayRouterBuilder.pipe(NodeServer.listen({ port: config.port }))),
  T.provide(ApiLayer),
  Logger.withMinimumLogLevel(LogLevel.All),
)

runMain(main)


```

**Comment by sukovanej** [comment]
Hey, I tried adjusting the code snippet you shared so I can run it and I can't reproduce. Please, share a minimal repro or a snippet that compiles.

**Comment by kattsushi** [comment]
sure here is the stackblitz for the repo https://stackblitz.com/edit/stackblitz-starters-8bptu2?file=index.ts

<img width="1161" alt="Screenshot 2024-08-03 at 4 23 09 p m" src="https://github.com/user-attachments/assets/5c4a712c-f568-46d8-b7d6-31370a808eee">

also i realized that at the botton-right appears an ivalid note, im not sure if is releated

but clicking says this error

```
{
  "schemaValidationMessages": [
    {
      "level": "error",
      "message": "Can't read from file https://stackblitzstarters8bptu2-cdb4--3000--41692973.local-credentialless.webcontainer.io/api/openapi.json"
    }
  ]
}
```

<img width="167" alt="Screenshot 2024-08-03 at 4 24 58 p m" src="https://github.com/user-attachments/assets/a9312db1-aecc-4e76-b8fa-17ae51daa9e7">

**Comment by sukovanej** [comment]
Hey, fix released. Thank you, nice catch!
