### ISSUE TITLE
Security.apiKeyy "query" should not use schemaBodyUrlParams

### ISSUE THREAD

**Issue by danielo515** [sukovanej/effect-http#655]
Hello.
Again, thank you for this great library.

I was trying to use the apiKey helper, and I wanted the api-key to be in the url search params, so intuitively I picked the option "query".
However, after some frustrating errors testing it, I decided to look at the implementation:

```ts
export const apiKey = (
  options: Security.ApiKeyOptions
): Security.Security<string> => {
  const schema = Schema.Struct({ [options.key]: Schema.String })

  const parse = pipe(
    options.in === "query"
      ? HttpServerRequest.schemaBodyUrlParams(schema)
      : HttpServerRequest.schemaHeaders(schema),
    Effect.map((obj) => obj[options.key]),
    Effect.mapError(() => HttpError.unauthorized(`Expected ${options.key} (${options.in}) api key`))
  )
```

I am not very experienced with effect, so I had to investigate what schemaBodyUrlParams actually does, and it seems to be used for "form requests", not url query params (which I think is what the original intention was).

I built my own implementation, and indeed now it works as expected:

```ts
export const apiKey = () => {
  const schema = Schema.Struct({ apiKey: Schema.String });

  const parse = pipe(
    HttpServerRequest.schemaSearchParams(schema),
    Effect.flatMap((obj) => ServerToken.validateToken(obj.apiKey)),
    Effect.mapError((x) =>
      HttpError.unauthorized(`Expected apiKey (query) api key`)
    )
  );

  return Security.make(parse, {
    apiKey: {
      name: "apiKey",
      type: "apiKey",
      in: "query",
    },
  });
};
```

To be clear my expectation was that I can query the API like this:

```
➜ http POST http://localhost:4321/api/expenses\?apiKey\="test"
HTTP/1.1 401 Unauthorized
Access-Control-Allow-Origin: *
Connection: keep-alive
Date: Sat, 10 Aug 2024 22:10:52 GMT
Keep-Alive: timeout=5
content-length: 31
content-type: text/plain

Expected apiKey (query) api key
```

But as you can see in the error message, I was always getting the apiKey in query errror.
I assume most people just uses the header and that's why nobody noticed until now?

**Comment by sukovanej** [comment]
Yop, that's a bug. I merged the fix and will release it in a moment. Thank you!

**Comment by danielo515** [comment]
Oh, Ok. I was feeling dumb that, after my solution was working, I was not able to make it type check.
I looked at the code in my editor and I saw it was not properly removing the dependency, and then I went to github and saw it was indeed being handled, and I felt dumb for not being in the latest version.
But in reality it was you doing an impressively fast PR and release!! Thanks
