### ISSUE TITLE
Is the generated client expected to run on a browser?

### ISSUE THREAD

**Issue by danielo515** [sukovanej/effect-http#666]
Hello again.
I just build an custom security for cookie auth (check #665) but when I try to generate the frontend client I get a bundle error.
The problem is that the api-spec is requiring the security module, and the security module implementation uses oslo (which uses native node modules) it is failed to being bundled.
I'm not sure how can I better decouple the api security so it is not part of the generated client.
I tried separating implementation from definition, but I suspect the usage of barrel index files is diminishing my efforts.
Before I continue trying, I want to know if this is a supported scenario or if it was intended for mock/testing/cli

**Comment by adrian-gierakowski** [comment]
Yes, it is meant to be used in the browser, and security implantation should not be leaked to the client. See: https://github.com/sukovanej/effect-http/issues/569

**Comment by danielo515** [comment]
Ok, thank you for confirming.
It took me several iterations to get the right code split so the backend code does not ship into the client.
Thanks
