### ISSUE TITLE
'Cannot encode Declaration to OpenAPISchema' when using Schema.DateFromSelf

### ISSUE THREAD

**Issue by danielo515** [sukovanej/effect-http#667]
Hello.
I'm getting the following error:

```
file:///Users/danielo/GIT/dharma-scripts/node_modules/.pnpm/effect-http@0.77.5_@effect+platform@0.62.4_@effect+schema@0.71.3_effect@3.6.7/node_modules/effect-http/dist/esm/internal/open-api.js:537
          throw new Error(`Cannot encode Declaration to OpenAPISchema, please specify OpenApi annotation for custom schemas`);
                ^

Error: Cannot encode Declaration to OpenAPISchema, please specify OpenApi annotation for custom schemas
```

When trying to use `Schema.DateFromSelf`. The reason I want to use that, is because my database is already sending me the events as parsed Dates. Any idea about how to deal with this?

**Comment by sukovanej** [comment]
You'd need to specify the OpenApi annotation. And I think you should rather use the `Date` schema which is meant to be JSON serialisable. If your motivation is a potential code duplication, you could employ combinators like `Schema.omit` / `Schema.pick` / ... to construct the HTTP API schema based on another schema.

**Comment by danielo515** [comment]
Yes, indeed. The problem was that I didn't know why was it not being serializable, but now that I discovered it is the dates, I can very easily work around it.
Thanks
